const  initialState = {
    win: {
        width: ((window.innerWidth < 1617) ? 1617 : window.innerWidth),
        height: ((window.innerHeight < 785) ? 785 : window.innerHeight),
    },
    hubConnection: null,
    autoload: false,
    defaultPicker: "#1e88e5ff",
    errorPicker: "#ff0000ff",
    successPicker: "#298535ff",
    balloonShape:"Octagon",
    balloonMode: "light",
    balloonFont: 0,
    MinMaxOneDigit: "0.5",
    MinMaxTwoDigit: "0.5",
    MinMaxThreeDigit: "0.5",
    MinMaxFourDigit: "0.5",
    MinMaxAngles: "1/2",
    routerno: "",
    MaterialQty: "",
    controllCopy: [],
    rectPadding: 10,
    rectWidth: 170,
    rectHeight:60,
    Convert_to_mm: false,
    accurateGDT: false,
    templatetype: "",
    exportTemplate: [],
    gridKey:0,
    maxsize: 32767,
    maxScaleSize: 12800,
    max_upload_file:5,
    aspectRatio: 16 / 9,
    scrollPosition: 0,
    konvaPositionTop:0,
    documentPositionTop: 0,
    moveScrollPosition: 0,
    selectedRowIndex:null,
    fitscreen: false,
    zoomed: false,
    prev: null,
    zoomingfactor: 0,
    pad: 20,
    width: 100,
    height: 100,
    drawingNo: "",
    revNo: "",
    loadingText : "",
    sidebarIsOpen: false,
    rightPanelOpen: false,
    identifyMode: 'off', // 'off', 'all', 'selected'
    _draggingBalloon: null, // { id, x, y } — live position during drag
    isLoading: false,
    isErrImage:false,
    topbarIsOpen: false,
    selectedRegion: "",
    bgImgRotation: 0,
    bgImgW: 100,
    bgImgH: 100,
    bgImgX: 100,
    bgImgY: 100,
    bgImgScale: 1,
    fontScale: 0,
    imgscale:1,
    ccFontScale: 0,
    InitialScale: 1,
    scaleStep:0,
    rotateX: 0,
    rotateY:0,
    ItemView: null,
    selectAnnotation: null,
    showdownloadComponent: false,
    convertStagesToImages:[],
    history: [],
    shapeHistory: [],
    shapeHistoryIndex: -1,
    user: JSON.parse(sessionStorage.getItem('user')) || [],
    roles: JSON.parse(sessionStorage.getItem('roles')) || [],
    sessionId: "",
    draft: [],
    partial_image: [],
    resized_image: [],
    immutableStore: [],
    drawingDetails: [],
    drawingHeader: [],
    drawingRegions: [],
    balloonRegions: [],
    originalRegions: [],
    zoomoriginalRegions: [],
    lmtype: [],
    lmsubtype: [],
    units: [],
    InstrumentSerials:[],
    Characteristics:[],
    cmbTolerance: [],
    balloonShapes: ['Circle', 'Ring', 'Star', 'Triangle', 'Square', 'Diamond', 'Pentagon', 'Hexagon', 'Octagon', 'Wedge', 'Tooltip-Down', 'Tooltip-UP', 'Tooltip-Left', 'Tooltip-Right'],
    savedDetails:false,
    loadingTextSize: "30px",
    scrollHeight: window.scrollY,
    isDisabledSearchBtn:false,
    isDisabledACT: true,
    isDisabledFIT: true,
    isDisabledZoomOut: true,
    isDisabledZoomIn: true,
    isDisabledCCW: true,
    isDisabledCW: true,
    isDisabledMAG: true,
    isDisabledFH: true,
    isDisabledDel: true,
    isDisabledSave: true,
    isDisabledReset: false,
    isDisabledResetB: true,
    isDisabledAutoB: true,
    isDisabledOCR: true,
    isDisabledMove: true,
    isDisabledRegion: true,
    isDisabledSPL: true,
    isDisabledSelected: true,
    isDisabledManual: true,
    isDisabledUnSelected:true,
    intBubble: 0,
    isMultifile: false,
    selectedBalloon:null,
    selectedGridBalloons: [],
    is_BalloonDrawingSaved: false,
    AppSettings: [],
    setImages: [],

    // Watermark settings
    watermark: {
        enabled: false,
        text: "DRAFT",
        fontSize: 48,
        fontFamily: "Calibri",
        fontWeight: "bold",
        color: "#888888",
        opacity: 0.15,
        rotation: -30,
        layout: "tiled",      // 'single', 'tiled', 'diagonal'
        position: "center",   // 'center', 'top-left', 'top-right', 'bottom-left', 'bottom-right'
        spacingX: 400,
        spacingY: 250,
        customX: null,
        customY: null,
    },

};

export default initialState;